numpy append

In [ ]:
import numpy as np

arr_1 = np.array([[1,2,3,4]])
arr_2 = np.array([[5,6,7,8]])
res = np.concatenate(arr_1,arr_2)
print(res)


In [ ]:
import numpy as np

arr_1 = np.array([[1,2,3,4]])
arr_2 = np.array([[5,6,7,8]])
res = np.concatenate((arr_1,arr_2))
print(res)


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])
res = np.concatenate((arr_1,arr_2))
print(res)


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7])
res = np.concatenate((arr_1,arr_2))
print(res)


In [ ]:
import numpy as np

arr_1 = np.array([[1,2,3,4]])
arr_2 = np.array([[5,6,7]]) # one less element # error
res = np.concatenate((arr_1,arr_2))
print(res)


In [11]:
import numpy as np
arr_1 = np.array([11,22,33,4,55,5,5,5,5,5,5,])
res = np.unique(arr_1)
print(res)

[ 4  5 11 22 33 55]


In [12]:
import numpy as np

arr = np.array([[1,2,3,4],[1,2,3]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [15]:
import numpy as np

arr = np.array([[1,2,3,4]])
print(arr)
print(np.any(arr))

[[1 2 3 4]]
True


In [16]:
import numpy as np

arr = np.array([[1,2,3,4]])
print(arr)
print(np.all(arr))

[[1 2 3 4]]
True


In [17]:
import numpy as np

arr = np.array([[1,2,3,4,0]])
print(arr)
print(np.any(arr))

[[1 2 3 4 0]]
True


In [25]:
import numpy as np

arr = np.array([[1,2,3,4]])
print(arr)
arr1 = arr > 2
# print(np.nan(arr))
# print(np.nan(arr1))
print(np.any(arr1))

[[1 2 3 4]]
True
