install numpy

In [ ]:
!pip install numpy

upgrade pip

In [ ]:
!python.exe -m pip install --upgrade pip

crate 2D array

In [ ]:
import numpy as np


Create 3D array

In [ ]:
import numpy as np

#arr = np.array([[[1,2,3,4,5],[6,7,8,9] ],[[1]]])
arr = np.array(
    [ # 3d
        [ #2
           [1]
        ],

    ]) # 3d


print(arr)
print(np.shape(arr)) # call shape function from np and apply to arr



4th D array

In [ ]:
import numpy as np

arr = np.array(
    [
        [
            [
                [1,2,3,4]
            ]
        ]
    ]
)

print(arr)

experiment : comment inside works

In [ ]:
import numpy as np

arr = np.array(
    [
        [
            [
                [1,2,3,4] # 1 D array
            ]
        ]
    ]
)

print(arr)

t4 ; np.zeros(7) # fill zeros

In [ ]:
import numpy as np

arr = np.zeros(1) # 1D array
print(arr,"1D array")
#arr = np.zeros(1,1)
arr = np.zeros( (1,1)) # 2D array
print(arr)

arr = np.zeros((1,1,1))
print(arr)

arr = np.zeros(())




In [ ]:
import numpy as np

arr = np.zeros(())
print(arr)

In [ ]:
import numpy as np

arr = np.zeros() # blank
print(arr)

In [ ]:
import numpy as np

arr = np.zeros(())
print(arr, " 0D array")

arr = np.zeros((1))
print(arr, " 1D array")

arr = np.zeros((1,1))
print(arr, " 2D array")

arr = np.zeros((1,2))
print(arr, " 1D array")

arr = np.zeros((1,1,1))
print(arr, " 3D array")



In [ ]:
import numpy as np

arr = np.zeros((2))
print(arr, " 1D array")
#
arr = np.zeros((2,2))
print(arr, " 1D rray")
#


In [ ]:
import numpy as np
arr = np.array(
    [ #2D array
        [0, 0, 0, 0, 0] # 1D arr
    ])

print("shape : ",np.shape(arr))

print(arr)

In [ ]:
import numpy as np
arr = np.array(
    [ #2D array
        [0, 0, 0, 0, 0], # 1D arr
        [1,1,1,1,1] #
    ])

print("shape : ",np.shape(arr))

print(arr)

In [ ]:
import numpy as np
arr = np.ones( (3,7)) # 3 rows 7 columns
print("shape : ",np.shape(arr))

print(arr)

In [ ]:
import numpy as np
arr = np.ones( (1,1,1))
print("shape : ",np.shape(arr))

print(arr)

In [ ]:
import numpy as np
arr = np.ones( (1,2,3))
print("shape : ",np.shape(arr))

print(arr)

In [ ]:
import numpy as np

arr = np.zeros((1,5))
print(arr, " 1D array")



In [53]:
import numpy as np
arr = np.ones( (3,3,3))
print("shape : ",np.shape(arr))

print(arr)

shape :  (3, 3, 3)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
[
    [
        [1. 1. 1.],
        [1. 1. 1.]
    ]

    [
        [1. 1. 1.],
        [1. 1. 1.]
    ]

    [
        [1. 1. 1.],
        [1. 1. 1.]
    ]
]

In [57]:
import numpy as np

arr = np.arange(5)
print(arr, " 1D array")
arr = np.arange(1,5)
print(arr, " 1D array")
arr = np.arange(2,5,2)
print(arr, " 1D array")


[0 1 2 3 4]  1D array
[1 2 3 4]  1D array
[2 4]  1D array


In [60]:
import numpy as np

arr = np.linspace(1,10,5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


In [62]:
import numpy as np

arr = np.full((3,2),"hii")

print(arr)


[['hii' 'hii']
 ['hii' 'hii']
 ['hii' 'hii']]


In [65]:
import numpy as np

arr = np.full((3,2),"hii")

print(arr)


[['hii' 'hii']
 ['hii' 'hii']
 ['hii' 'hii']]
