boolean indexing

In [ ]:
import numpy as np

arr = np.array([10.20,30,40,50,60])
boolean_index_1 = arr[[True,True,True,False,False]]
print(boolean_index_1)
boolean_index_2 = arr[arr > 10]
print(boolean_index_2)
boolean_index_3 = arr[arr < 10]
print(boolean_index_3)

boolean_index_4  = arr[True]
print(boolean_index_4)

boolean_index_5  = arr[False]
print(boolean_index_5)



condition based greater than less than

In [ ]:
import numpy as np

arr = np.array([10.20,30,40,50,60])
boolean_result = arr[ arr > 20 &  arr < 60]

In [25]:
import numpy as np

arr = np.array([10.20,30,40,50,60])
boolean_result = [ (arr > 20) &  ( arr < 60) ]
print(boolean_index_1)
boolean_result =  (arr > 20) &  ( arr < 60)
print(boolean_result)



[10.2 30.  40. ]
[False  True  True  True False]


In [ ]:
actual results

In [ ]:
import numpy as np

arr = np.array([10.20,30,40,50,60])
boolean_result = arr[ (arr > 20) &  ( arr < 60) ]
print(boolean_index_1)

print(actual_result)

np.where( <condition> )

In [26]:
import numpy as np

arr = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,0]
])
result = np.where(arr > 5)
print(result)


(array([1, 1, 2, 2]), array([1, 2, 0, 1]))


condition on 2D array , filtering.

In [28]:
import numpy as np

arr = np.array([1,2,3])
result = np.where(arr > 5)
print(result)
result = np.where(arr > 2)
print(result)


(array([], dtype=int64),)
(array([2]),)


In [30]:
import numpy as np

arr = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,0]
])

# convert or change values less than 5
print(arr)
arr > 5 = 999 # syntax error
print(arr)

SyntaxError: cannot assign to comparison (2657342709.py, line 11)

In [33]:
import numpy as np

arr = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,0]
])

# convert or change values less than 5
print(arr)
arr[ arr > 5 ] = 999 # syntax error
print(" now changes numpy array \n")
print(arr)

[[1 2 3]
 [5 6 7]
 [8 9 0]]
 now changes numpy array 

[[  1   2   3]
 [  5 999 999]
 [999 999   0]]


math operations !

In [ ]:
import numpy as np

arr = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,0]
])

# convert or change values less than 5
print(arr)
arr[ arr > 5 ] = 999 # syntax error
print(" now changes numpy array \n")
print(arr)
# use case ! used to retire workers whose age is greataer than 62
#


mathematical operations , 1 D to scalar

In [35]:
import numpy as  np
arr = np.array([1,2,3,4,5])
print(arr)
arr + 10
print(arr)
total =arr + 10
print(total)

[1 2 3 4 5]
[1 2 3 4 5]
[11 12 13 14 15]


In [36]:
import numpy as  np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
total = arr1 + arr2
print(total)

[ 2  4  6  8 10]


In [38]:
import numpy as  np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
total_subtract_arr1_from_arr2 = arr2 - arr1
print(total_subtract_arr1_from_arr2)
total_subtract_arr2_from_arr1 = arr1 - arr2
print(total_subtract_arr2_from_arr1)
# element wise operations


[0 0 0 0 0]
[0 0 0 0 0]


In [41]:
import numpy as  np
arr1 = np.array([[1,2,3,4,5],[11,22,33,44,55]])
arr2 = np.array([[1,2,3,4,5],[110,220,330,440,550]])
total = arr1 + arr2
print(total)

[[  2   4   6   8  10]
 [121 242 363 484 605]]


mathematical operations on 2D array + scalar arrray

In [42]:
import numpy as  np
arr1 = np.array([[1,2,3,4,5],[11,22,33,44,55]])
result = arr1 + 10
print(" arr1 : ", arr1)
print(" result of arr1 + 10 is : " , result)


 arr1 :  [[ 1  2  3  4  5]
 [11 22 33 44 55]]
 result of arr1 + 10 is :  [[11 12 13 14 15]
 [21 32 43 54 65]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(np.add(a, 5))       # [6 7 8 9]
print(np.subtract(a, 1))  # [0 1 2 3]
print(np.multiply(a, 2))  # [2 4 6 8]
print(np.divide(a, 2))    # [0.5 1. 1.5 2.]

In [46]:
import numpy as np
a = np.array([1,2,3,4,5])
print(np.add(a,5))
print(np.subtract(a,1))
print(np.multiply([1,2,3,4],12))

[ 6  7  8  9 10]
[0 1 2 3 4]
[12 24 36 48]
